'use client';
/**
 * Printable acknowledgement slip for DEMO builds. In production the slip is a
 * PDF generated by the workers and served from object storage via a signed URL.
 */
import Image from 'next/image';
import { useEffect, useState } from 'react';
import QRCode from 'qrcode';
import { ENTRY_TYPE_LABELS, QUALIFICATION_LABELS, STATE_BY_CODE } from '@armyx/shared';
import { DEMO } from '@/lib/api';

export default function SlipPage() {
  const [slip, setSlip] = useState<null | { app: any; photo?: string; qr: string; title: string }>(null);
  const [msg, setMsg] = useState('Loading…');

  useEffect(() => {
    if (!DEMO) return setMsg('Download your slip from the dashboard.');
    (async () => {
      const { load } = await import('@/lib/demo/store');
      const s = load();
      const app = s.apps.find((a) => a.userId === s.sessionUserId);
      if (!app) return setMsg('No submitted application. Sign in and submit first.');
      const verifyUrl = `${location.origin}/verify?id=${encodeURIComponent(app.applicationNo)}&s=demo`;
      setSlip({ app, photo: s.docs[app.userId]?.find((d) => d.type === 'passport_photo')?.dataUrl, qr: await QRCode.toDataURL(verifyUrl, { margin: 1, width: 240 }), title: s.exercise.title });
    })();
  }, []);

  if (!slip) return <p className="container-x py-16 text-muted">{msg}</p>;
  const d = slip.app.data;
  const rows: [string, string][] = [
    ['Full name', `${d.personal.surname.toUpperCase()} ${d.personal.firstName} ${d.personal.middleName ?? ''}`],
    ['Gender', d.personal.gender === 'male' ? 'Male' : 'Female'],
    ['Date of birth', d.personal.dateOfBirth],
    ['State of origin / LGA', `${STATE_BY_CODE[d.origin.stateOfOrigin]?.name} / ${d.origin.lga}`],
    ['Entry type', ENTRY_TYPE_LABELS[d.entry.entryType as keyof typeof ENTRY_TYPE_LABELS]],
    ['Highest qualification', QUALIFICATION_LABELS[d.education.highestQualification as keyof typeof QUALIFICATION_LABELS]],
    ['Height', `${(d.physical.heightCm / 100).toFixed(2)} m`],
    ['Preferred screening state', STATE_BY_CODE[d.entry.preferredScreeningState]?.name ?? ''],
    ['Next of kin', `${d.next_of_kin.fullName} (${d.next_of_kin.relationship})`],
  ];
  return (
    <div className="container-x max-w-3xl py-8 print:p-0">
      <div className="mb-4 flex justify-end gap-2 print:hidden">
        <button className="btn-primary" onClick={() => window.print()}>Print / save as PDF</button>
      </div>
      <article className="overflow-hidden border border-olive-100 bg-white shadow-card print:shadow-none">
        <header className="flex items-center gap-4 border-b-4 border-gold-500 bg-olive-800 p-5 text-white">
          <Image src="/images/crest.png" alt="" width={64} height={64} className="h-16 w-16 rounded-full" />
          <div>
            <p className="font-serif text-2xl font-bold">NIGERIAN ARMY</p>
            <p className="text-sm">{slip.title.toUpperCase()}</p>
            <p className="text-sm font-bold text-gold-300">APPLICATION ACKNOWLEDGEMENT SLIP — DEMO</p>
          </div>
        </header>
        <div className="grid gap-6 p-6 sm:grid-cols-[1fr_auto]">
          <div>
            <p className="text-xs text-muted">Application number</p>
            <p className="font-mono text-2xl font-bold text-olive-800">{slip.app.applicationNo}</p>
            <p className="text-xs text-muted">Submitted: {new Date(slip.app.submittedAt).toUTCString()}</p>
            <dl className="mt-5 space-y-2 text-sm">
              {rows.map(([k, v]) => <div key={k} className="grid grid-cols-[11rem_1fr] gap-2"><dt className="text-muted">{k}</dt><dd className="font-semibold">{v}</dd></div>)}
            </dl>
          </div>
          <div className="flex h-40 w-32 items-center justify-center border border-khaki-500 bg-sand text-center text-xs text-muted">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            {slip.photo ? <img src={slip.photo} alt="Passport photograph" className="h-full w-full object-cover" /> : 'Passport photo'}
          </div>
        </div>
        <div className="flex items-center gap-4 border-t border-olive-100 p-6">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={slip.qr} alt="Verification QR code" className="h-28 w-28" />
          <p className="text-sm"><strong>Verify this slip:</strong> scan the QR code. Screening officers use it to confirm the slip is genuine.</p>
        </div>
        <div className="border-t-2 border-gold-500 p-6 text-sm">
          <p className="font-bold">IMPORTANT INSTRUCTIONS</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Print this slip and bring it with your ORIGINAL credentials to the screening venue.</li>
            <li>Your screening venue and date will be shown on the portal dashboard and sent by email/SMS.</li>
            <li>Recruitment into the Nigerian Army is FREE. Do not pay anyone for any reason.</li>
          </ul>
          <p className="mt-4 text-center text-xs font-bold text-danger">DEMONSTRATION ONLY — NOT A VALID DOCUMENT</p>
        </div>
      </article>
    </div>
  );
}
