apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: armyx
resources:
  - namespace.yaml
  - config.yaml
  - postgres-cnpg.yaml
  - pgbouncer.yaml
  - api.yaml
  - workers.yaml
  - web.yaml
  - cms.yaml
  - autoscaling.yaml
  - migrate-job.yaml
  - ingress.yaml
  - network-policies.yaml
  - monitoring.yaml
