/**
 * Queue names and job payload contracts shared between the API (producer)
 * and the workers (consumers). Changing a payload shape is a breaking change:
 * deploy workers that understand both shapes first.
 */
export const QUEUES = {
  submissions: 'submissions',
  drafts: 'drafts',
  notifications: 'notifications',
  pdf: 'pdf',
  exports: 'exports',
  documents: 'documents',
  contact: 'contact',
  maintenance: 'maintenance',
} as const;
export type QueueName = (typeof QUEUES)[keyof typeof QUEUES];

export interface SubmissionJob {
  applicationId: string; // uuid generated by the API
  applicationNo: string;
  userId: string;
  exerciseId: string;
  submittedAt: string;
  /** Age on the exercise closing date, computed by the API at submission. */
  age: number;
  /** Base64 of the AES-GCM encrypted ApplicationData snapshot (never plaintext PII in Redis). */
  payloadEnc: string;
  ipHash: string;
}

export interface DraftPersistJob {
  userId: string;
  exerciseId: string;
}

export type NotificationTemplate =
  | 'otp'
  | 'welcome'
  | 'submission_received'
  | 'status_changed'
  | 'screening_invite'
  | 'password_reset'
  | 'admin_invite';

export interface NotificationJob {
  channel: 'email' | 'sms';
  /** Recipient is resolved by the worker from userId when `to` is omitted, so PII is not stored in Redis. */
  userId?: string;
  to?: string;
  template: NotificationTemplate;
  vars: Record<string, string>;
}

export interface PdfSlipJob {
  applicationId: string;
}

export interface ExportJob {
  exportId: string;
}

export interface DocumentVerifyJob {
  documentId: string;
}

export interface ContactJob {
  name: string;
  email: string;
  phone?: string;
  subject: string;
  message: string;
  ipHash: string;
}

/** Redis key helpers used by both API and workers. */
export const RK = {
  session: (id: string) => `sess:${id}`,
  userSessions: (userId: string) => `usess:${userId}`,
  draft: (userId: string, exerciseId: string) => `draft:${exerciseId}:${userId}`,
  appStatus: (userId: string, exerciseId: string) => `appst:${exerciseId}:${userId}`,
  activeExercise: () => 'ref:exercise:active',
  statsState: (exerciseId: string) => `stats:${exerciseId}:state`,
  statsStatus: (exerciseId: string) => `stats:${exerciseId}:status`,
  statsEntry: (exerciseId: string) => `stats:${exerciseId}:entry`,
  statsDaily: (exerciseId: string) => `stats:${exerciseId}:daily`,
  statsTotal: (exerciseId: string) => `stats:${exerciseId}:total`,
} as const;
